language: node_js
node_js:
  - "20"

services:
  - docker


script:
  - npm install
  - npm test
  - npm run build
  - docker build -t movie-reservation-system .
  - docker run -d -p 8080:80 movie-reservation-system
